
list1_base_url = "insert base url to test here"
product_key_url = "&productkeys="
list2_base_url = "insert 2nd base url to test here"
list1 = []
list2 = []

market_list = [
"Albany",
"Altoona",
"Baltimore",
"Boston",
"Buffalo",
"Charleston+WV",
"Harrisburg",
"Hartford/New+Haven",
"New+York",
"Norfolk",
"Philadelphia",
"Pittsburgh",
"Portland+ME",
"Providence",
"Richmond",
"Rochester",
"Springfield+MA",
"Syracuse",
"Washington+DC",
"Wilkes-Barre",
"Atlanta",
"Augusta",
"Austin",
"Baton+Rouge",
"Birmingham",
"Charleston+SC",
"Charlotte",
"Chattanooga",
"Columbia",
"Dallas-Ft.+Worth",
"El Paso",
"Ft.+Myers/Naples",
"Greensboro",
"Greenville",
"Houston",
"Huntsville",
"Jackson",
"Jacksonville",
"Kingsport/Tri+Cities",
"Knoxville",
"Little Rock",
"Lubbock",
"Macon",
"Memphis",
"Miami/Ft.+Lauderdale",
"Mobile",
"Montgomery",
"Nashville",
"New Orleans",
"Oklahoma+City",
"Orlando/Melbourne",
"Raleigh",
"San+Antonio",
"Savannah",
"Shreveport",
"Tampa/Sarasota",
"Tulsa",
"West+Palm+Beach",
"Anchorage",
"Boise",
"Eugene",
"Portland",
"Seattle",
"Spokane",
"Albuquerque",
"Bakersfield",
"Colorado+Springs",
"Denver",
"Fresno",
"Las+Vegas",
"Los+Angeles",
"Monterey",
"Palm+Springs",
"Phoenix",
"Reno",
"Sacramento",
"Salt+Lake+City",
"San+Diego",
"San+Francisco",
"Santa+Barbara",
"Tucson",
"Cincinnati",
"Cleveland",
"Columbus",
"Davenport",
"Dayton",
"Des+Moines",
"Detroit",
"Evansville",
"Fort+Wayne",
"Grand+Rapids",
"Green+Bay",
"Indianapolis",
"Kansas+City",
"Lansing",
"Lexington",
"Lincoln",
"Louisville",
"Madison",
"Milwaukee",
"Minneapolis",
"Omaha",
"South+Bend",
"Springfield+MO",
"St.+Louis",
"Toledo",
"Wichita",
"Chicago",
"Peoria",
"Rockford"]
